//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FolderAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class attribute
    {
        public System.Guid attributeid { get; set; }
        public string name { get; set; }
        public string value { get; set; }
        public System.Guid files_filesid { get; set; }
    
        public virtual files file { get; set; }
    }
}
