//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FolderAnalysis
{
    using System;
    using System.Collections.Generic;
    
    public partial class files
    {
        public files()
        {
            this.attributes = new HashSet<attribute>();
        }
    
        public System.Guid filesid { get; set; }
        public string file_name_full { get; set; }
        public string folder { get; set; }
        public string file { get; set; }
        public System.Guid session_sessionid { get; set; }
    
        public virtual ICollection<attribute> attributes { get; set; }
        public virtual session session { get; set; }
    }
}
